/*

​-- Script SQL:
-- 1 – Criação do banco de dados:
*/

CREATE DATABASE IF NOT EXISTS Oficina
	DEFAULT CHARSET utf8
	DEFAULT COLLATE utf8_general_ci;

USE Oficina;
/*

-- 2 – Criação das tabelas:
*/

CREATE TABLE IF NOT EXISTS CLIENTES (

    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL DEFAULT '',
    CPF INT UNIQUE NOT NULL ,
    EMAIL VARCHAR(50),
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS CARROS (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(10) NOT NULL DEFAULT '',
MODELO VARCHAR(15) NOT NULL DEFAULT '',
COR VARCHAR (10) NOT NULL DEFAULT '',
ANO INT NOT NULL,
ID_CLIENTE INT UNIQUE,

FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID)
ON DELETE RESTRICT
ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS TELEFONES (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TELEFONE INT NOT NULL,
TIPO ENUM ('RES','CEL'),
ID_CLIENTE INT NOT NULL,

FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID)
ON DELETE RESTRICT
ON UPDATE CASCADE

);
/*

-- 3 – Inserção dos dados:
*/

INSERT INTO CLIENTES VALUES(NULL, 'LUIZ', '1234567','LUIZ@GMAIL.COM', 'SP', 'CAMPINAS');
INSERT INTO CLIENTES VALUES(NULL, 'PEDRO', '1234578521', 'PEDRO@GMAIL.COM', 'RJ', 'COBACABANA');
INSERT INTO CLIENTES VALUES(NULL, 'ANTONIO', '125556844', 'ANTONIO@BOL.COM', 'SP', 'VALINHOS');
INSERT INTO CLIENTES VALUES(NULL, 'CLAUDIO', '96455645', 'CLAUDIO@BOL.COM', 'RJ', 'PETROPOLES');
INSERT INTO CLIENTES VALUES(NULL, 'ROGERIO', '45465488', '', 'MG', 'CALDAS');
INSERT INTO CLIENTES VALUES(NULL, 'HENRIQUE', '65432155', 'HENRIQUE@GMAIL.COM', 'SP', 'DIADEMA');
INSERT INTO CLIENTES VALUES(NULL, 'JULIANA', '65154475', '', 'PR', 'PONTA GROSSA');
INSERT INTO CLIENTES VALUES(NULL, 'FRANCISCO', '61321548', 'FRANCISCO@GMAIL.COM', 'RJ', 'COPACABAMA');
INSERT INTO CLIENTES VALUES(NULL, 'CLAUDIO', '32154875', '', 'RJ', 'PETROPOLES');

INSERT INTO CARROS VALUES (NULL, 'CHEVROLET', 'CORSA', 'VERDE', 2009, 1);
INSERT INTO CARROS VALUES (NULL, 'FORD', 'FIESTA', 'AZUL', 1998, 2);
INSERT INTO CARROS VALUES (NULL, 'FORD', 'FOCUS', 'VERDE', 2006, 3);
INSERT INTO CARROS VALUES (NULL, 'CHEVROLET', 'PRISMA', 'VERMELHO', 2007, 4);
INSERT INTO CARROS VALUES (NULL, 'FIAT', 'DOBLO', 'AZUL', 2007, 5);
INSERT INTO CARROS VALUES (NULL, 'FORD', 'ECOSPORT', 'VERMELHO', 2007, 6);
INSERT INTO CARROS VALUES (NULL, 'FIAT', 'STILO', 'PRATA', 2007, 7);
INSERT INTO CARROS VALUES (NULL, 'CHEVROLET', 'ZAFIRA', 'PRETO', 2007, 8);
INSERT INTO CARROS VALUES (NULL, 'CHEVROLET', 'ZAFIRA', 'PRETO', 2007, 9);


INSERT INTO TELEFONES

VALUES

    (NULL, 19995587, 'RES', 1),
    (NULL, 19985547, 'CEL', 2),
    (NULL, 57454865, 'RES', 2),
    (NULL, 55458555, 'RES', 1),
    (NULL, 55457544, 'CEL', 3),
    (NULL, 32154255, 'CEL', 4),
    (NULL, 32157474, 'RES', 5),
    (NULL, 54321547, 'CEL', 5),
    (NULL, 32132158, 'RES', 6),
    (NULL, 32154321, 'CEL', 7),
    (NULL, 98765488, 'RES', 8),
    (NULL, 32146547, 'CEL', 9);



/*

-- 4 – Consulta:
A OFICINA PORCA & CONTRA PORCA ESTA FAZENDO UMA CAMPANHA PARA REVISÃO DOS VEICULOS DE SEUS CLIENTES,
DEVIDO AS FESTAS DE FINAL DE ANO, NO INTUITO DE GARANTIR UMA VIAGEM SEGURA, PARA ISSO SERÁ NESCESSARIO
QUE SEJAM CONTACTADOS VIA TELEFONE OS CLIENTES COM VEICULO DA MARCA FORD.
E POR EMAIL OS CLIENTES DE VEICULO CHEVROLET.
*/

SELECT NOME, TELEFONE, TIPO, MARCA FROM CLIENTES 
    INNER JOIN TELEFONES
        ON CLIENTES.ID = TELEFONES.ID_CLIENTE
    INNER JOIN CARROS
        ON CLIENTES.ID = CARROS.ID_CLIENTE
            WHERE MARCA = 'CHEVROLET'

;

/*

+---------+----------+------+-----------+

| NOME | TELEFONE | TIPO | MARCA |

+---------+----------+------+-----------+

| LUIZ | 19995587 | RES | CHEVROLET |

| LUIZ | 55458555 | RES | CHEVROLET |

| CLAUDIO | 54556548 | CEL | CHEVROLET |

+---------+----------+------+-----------+

*/

SELECT NOME, EMAIL, MARCA FROM CLIENTES 
    INNER JOIN CARROS
        ON CLIENTES.ID = CARROS.ID_CLIENTE
        WHERE MARCA = 'FORD'

;

/*
+---------+-----------------+-------+
|   NOME  | EMAIL           | MARCA |
+---------+-----------------+-------+
| PEDRO   | PEDRO@GMAIL.COM |  FORD |
| ANTONIO | ANTONIO@BOL.COM |  FORD |
+---------+-----------------+-------+
*/

/* Durante a pandemia, a oficina Porca & Contraporca esta realizando uma campanha de divulgação
de seus serviços domiciliares, para isso esta com uma campanha para complementar o cadastros
de seus clientes, sendo assim foi solicitado ao DBA que escrevesce um script para saber os clientes
que ainda não possuem email e telefone.

*/

select clientes.nome, telefones.telefone, telefones.tipo, clientes.email
    from clientes
        right join telefones
            on clientes.id = telefones.id_cliente order by email;

/*
+-----------+----------+------+---------------------+
| nome | telefone | tipo | email |
+-----------+----------+------+---------------------+
| ROGERIO | 32157474 | RES | |
| ROGERIO | 54321547 | CEL | |
| JULIANA | 32154321 | CEL | |
| CLAUDIO | 32146547 | CEL | |
| ANTONIO | 55457544 | CEL | ANTONIO@BOL.COM |
| CLAUDIO | 32154255 | CEL | CLAUDIO@BOL.COM |
| FRANCISCO | 98765488 | RES | FRANCISCO@GMAIL.COM |
| HENRIQUE | 32132158 | RES | HENRIQUE@GMAIL.COM |
| LUIZ | 19995587 | RES | LUIZ@GMAIL.COM |
| LUIZ | 55458555 | RES | LUIZ@GMAIL.COM |
| PEDRO | 19985547 | CEL | PEDRO@GMAIL.COM |

| PEDRO | 57454865 | RES | PEDRO@GMAIL.COM |

+-----------+----------+------+---------------------+

*/