/*

​-- Script SQL:
-- 1 – Criação do banco de dados:
*/

CREATE DATABASE IF NOT EXISTS Oficina
	DEFAULT CHARSET utf8
	DEFAULT COLLATE utf8_general_ci;

USE Oficina;
/*

-- 2 – Criação das tabelas:
*/

CREATE TABLE IF NOT EXISTS CLIENTE
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL DEFAULT '',
    CPF INT UNIQUE NOT NULL ,
    EMAIL VARCHAR(50),
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS CARRO
(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MARCA VARCHAR(10) NOT NULL DEFAULT '',
	MODELO VARCHAR(15) NOT NULL DEFAULT '',
	COR VARCHAR (10) NOT NULL DEFAULT '',
	ANO INT NOT NULL,
	ID_CLIENTE INT UNIQUE,

FOREIGN KEY 
	(ID_CLIENTE) REFERENCES CLIENTES (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS TELEFONE
(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TELEFONE INT NOT NULL,
	TIPO ENUM ('RES','CEL'),
	ID_CLIENTE INT NOT NULL,

FOREIGN KEY 
	(ID_CLIENTE) REFERENCES CLIENTES (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE

);
/*

-- 3 – Inserção dos dados:
*/

INSERT INTO CLIENTE
	VALUES
	(NULL, 'LUIZ', '1234567','LUIZ@GMAIL.COM', 'SP', 'CAMPINAS'),
	(NULL, 'PEDRO', '1234578521', 'PEDRO@GMAIL.COM', 'RJ', 'COBACABANA'),
	(NULL, 'ANTONIO', '125556844', 'ANTONIO@BOL.COM', 'SP', 'VALINHOS'),
	(NULL, 'CLAUDIO', '96455645', 'CLAUDIO@BOL.COM', 'RJ', 'PETROPOLES'),
	(NULL, 'ROGERIO', '45465488', '', 'MG', 'CALDAS'),
	(NULL, 'HENRIQUE', '65432155', 'HENRIQUE@GMAIL.COM', 'SP', 'DIADEMA'),
	(NULL, 'JULIANA', '65154475', '', 'PR', 'PONTA GROSSA'),
	(NULL, 'FRANCISCO', '61321548', 'FRANCISCO@GMAIL.COM', 'RJ', 'COPACABAMA'),
	(NULL, 'CLAUDIO', '32154875', '', 'RJ', 'PETROPOLES');
    

select 
	id,
	nome,
	cpf,
    email
from 
    cliente
;

truncate 
	cliente
;

INSERT INTO CARRO VALUES 
	(NULL, 'CHEVROLET', 'CORSA', 'VERDE', 2009, 1),
	(NULL, 'FORD', 'FIESTA', 'AZUL', 1998, 2),
	(NULL, 'FORD', 'FOCUS', 'VERDE', 2006, 3),
	(NULL, 'CHEVROLET', 'PRISMA', 'VERMELHO', 2007, 4),
	(NULL, 'FIAT', 'DOBLO', 'AZUL', 2007, 5),
	(NULL, 'FORD', 'ECOSPORT', 'VERMELHO', 2007, 6),
	(NULL, 'FIAT', 'STILO', 'PRATA', 2007, 7),
	(NULL, 'CHEVROLET', 'ZAFIRA', 'PRETO', 2007, 8),
	(NULL, 'CHEVROLET', 'ZAFIRA', 'PRETO', 2007, 9);


INSERT INTO TELEFONE
	VALUES
    (NULL, 19995587, 'RES', 1),
    (NULL, 19985547, 'CEL', 2),
    (NULL, 57454865, 'RES', 2),
    (NULL, 55458555, 'RES', 1),
    (NULL, 55457544, 'CEL', 3),
    (NULL, 32154255, 'CEL', 4),
    (NULL, 32157474, 'RES', 5),
    (NULL, 54321547, 'CEL', 5),
    (NULL, 32132158, 'RES', 6),
    (NULL, 32154321, 'CEL', 7),
    (NULL, 98765488, 'RES', 8),
    (NULL, 32146547, 'CEL', 9);



/*

-- 4 – Consulta:
A OFICINA PORCA & CONTRA PORCA ESTA FAZENDO UMA CAMPANHA PARA REVISÃO DOS VEICULOS DE SEUS CLIENTES,
DEVIDO AS FESTAS DE FINAL DE ANO, NO INTUITO DE GARANTIR UMA VIAGEM SEGURA, PARA ISSO SERÁ NESCESSARIO
QUE SEJAM CONTACTADOS VIA TELEFONE OS CLIENTES COM VEICULO DA MARCA FORD.
E POR EMAIL OS CLIENTES DE VEICULO CHEVROLET.
*/
SELECT * FROM CLIENTE;
SELECT * FROM TELEFONE;
SELECT * FROM CARRO;
SELECT 
	CLIENTE.NOME, 
    TELEFONE.TELEFONE, 
    TELEFONE.TIPO, 
    CARRO.MARCA
FROM 
	CLIENTE
INNER JOIN TELEFONE
	ON CLIENTE.ID = TELEFONE.ID_CLIENTE
INNER JOIN CARRO
	ON CLIENTE.ID = CARRO.ID_CLIENTE
		WHERE MARCA = 'CHEVROLET'
;

SELECT 
	cliente.NOME,
    cliente.EMAIL,
    carro.MARCA
FROM
	CLIENTE 
INNER JOIN 
	CARRO
	ON cliente.ID = carro.ID_CLIENTE
    WHERE MARCA = 'FORD'

;

/* Durante a pandemia, a oficina Porca & Contraporca esta realizando uma campanha de divulgação
de seus serviços domiciliares, para isso esta com uma campanha para complementar o cadastros
de seus clientes, sendo assim foi solicitado ao DBA que escrevesce um script para saber os clientes
que ainda não possuem email e telefone.

*/

select distinct
-- Escolha os Campos
	cliente.nome,
    telefone.telefone,
    telefone.tipo,
    cliente.email
from 
-- Escolha a tabela 1
	cliente
right join
-- Escolha a tabela 2
	telefones
-- Defina as restrições (CONSTRAINT) entre a Tabela 1 e 2
    on clientes.id = telefones.id_cliente
-- Defina a ordem que devem aparecer os dados
order by email;
